//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduate
    {
        public Graduate()
        {
            this.GraduateDegrees = new HashSet<GraduateDegree>();
            this.GraduateExperiences = new HashSet<GraduateExperience>();
            this.GraduateLanguages = new HashSet<GraduateLanguage>();
            this.JobApplications = new HashSet<JobApplication>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Profile { get; set; }
        public Nullable<int> CurrentStatusId { get; set; }
        public Nullable<int> VisaStatusId { get; set; }
        public Nullable<System.DateTime> AvailableFromDate { get; set; }
        public string PcSkills { get; set; }
        public string OtherSkills { get; set; }
        public string LinkedIn { get; set; }
        public string GooglePlus { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Lookup CurrentStatus { get; set; }
        public virtual User User { get; set; }
        public virtual Lookup VisaStatus { get; set; }
        public virtual ICollection<GraduateDegree> GraduateDegrees { get; set; }
        public virtual ICollection<GraduateExperience> GraduateExperiences { get; set; }
        public virtual ICollection<GraduateLanguage> GraduateLanguages { get; set; }
        public virtual ICollection<JobApplication> JobApplications { get; set; }
    }
}
