//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;

namespace Entities
{
    public static class Identifiers
    {
    	public enum LookupType
    	{
    		[Description("Current Status")]
    		CurrentStatus = 1,
    		[Description("Visa Status")]
    		VisaStatus = 2,
    		[Description("Proficiency")]
    		Proficiency = 3,
    		[Description("Recruitment Stage")]
    		RecruitmentStage = 4,
    		[Description("State")]
    		State = 5,
    		[Description("Date Posted")]
    		DatePosted = 6,
    		[Description("Job Type")]
    		JobType = 7,
    	}
    	public enum CurrentStatus
    	{
    		NA = 1,
    		Studying = 2,
    		Lookingforinternship = 3,
    		Internship = 4,
    		LookingforJob = 5,
    	}
    	public enum VisaStatus
    	{
    		NA = 100,
    		EUCitizen = 101,
    		StudyAndInternshipVisa = 102,
    		OrientationYearVisa = 103,
    		HighSkilledMigrantVisa = 104,
    	}
    	public enum Proficiency
    	{
    		BasicUnderstanding = 200,
    		Conversational = 201,
    		Fluent = 202,
    	}
    	public enum RecruitmentStage
    	{
    		Applied = 300,
    		InvitedforInterview = 301,
    		InvitedforInterview = 302,
    		ConductedInterview = 303,
    		OfferSent = 304,
    		Rejected = 305,
    		Recruited = 306,
    	}
    	public enum State
    	{
    	}
    	public enum DatePosted
    	{
    		AnyDate = 500,
    		Last30Days = 501,
    		Last7Days = 502,
    		Last3Days = 503,
    		SinceYesterday = 504,
    	}
    	public enum JobType
    	{
    		FreeLance = 600,
    		FullTime = 601,
    		Internship = 602,
    		PartTime = 603,
    		Temporary = 604,
    	}
    }
}
