//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Core.Annotations;

namespace Entities
{
    public static class Identifiers
    {
    	public enum LookupType
    	{
    		[Description("Current Status")]
    		CurrentStatus = 1,
    		[Description("Visa Status")]
    		VisaStatus = 2,
    		[Description("Proficiency")]
    		Proficiency = 3,
    		[Description("Recruitment Stage")]
    		RecruitmentStage = 4,
    		[Description("State")]
    		State = 5,
    		[Description("Date Posted")]
    		DatePosted = 6,
    		[Description("Job Type")]
    		JobType = 7,
    	}
    	public enum CurrentStatus
    	{
    		[Description("N/A")]
    		NA = 1,
    		[Description("Studying")]
    		Studying = 2,
    		[Description("Looking for internship")]
    		Lookingforinternship = 3,
    		[Description("Internship")]
    		Internship = 4,
    		[Description("Looking for Job")]
    		LookingforJob = 5,
    	}
    	public enum VisaStatus
    	{
    		[Description("N/A")]
    		NA = 100,
    		[Description("EU Citizen")]
    		EUCitizen = 101,
    		[Description("Study & Internship Visa")]
    		StudyAndInternshipVisa = 102,
    		[Description("Orientation Year Visa")]
    		OrientationYearVisa = 103,
    		[Description("High Skilled Migrant Visa")]
    		HighSkilledMigrantVisa = 104,
    	}
    	public enum Proficiency
    	{
    		[Description("Basic Understanding")]
    		BasicUnderstanding = 200,
    		[Description("Conversational")]
    		Conversational = 201,
    		[Description("Fluent")]
    		Fluent = 202,
    	}
    	public enum RecruitmentStage
    	{
    		[Description("Applied")]
    		Applied = 300,
    		[Description("Invited for Interview")]
    		InvitedforInterview = 301,
    		[Description("Conducted Interview")]
    		ConductedInterview = 302,
    		[Description("Offer Sent")]
    		OfferSent = 303,
    		[Description("Rejected")]
    		Rejected = 304,
    		[Description("Recruited")]
    		Recruited = 305,
    	}
    	public enum State
    	{
    	}
    	public enum DatePosted
    	{
    		[Description("Any Date")]
    		AnyDate = 500,
    		[Description("Last 30 Days")]
    		Last30Days = 501,
    		[Description("Last 7 Days")]
    		Last7Days = 502,
    		[Description("Last 3 Days")]
    		Last3Days = 503,
    		[Description("Since Yesterday")]
    		SinceYesterday = 504,
    	}
    	public enum JobType
    	{
    		[Badge("label-success")]
    		[Description("Freelance")]
    		Freelance = 600,
    		[Badge("label-warning")]
    		[Description("Full-Time")]
    		FullTime = 601,
    		[Badge("label-info")]
    		[Description("Internship")]
    		Internship = 602,
    		[Badge("label-inverse")]
    		[Description("Part-Time")]
    		PartTime = 603,
    		[Badge("label-default")]
    		[Description("Temporary")]
    		Temporary = 604,
    	}
    }
}
