//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public Lookup()
        {
            this.Graduates = new HashSet<Graduate>();
            this.Graduates1 = new HashSet<Graduate>();
            this.GraduateLanguages = new HashSet<GraduateLanguage>();
            this.JobApplications = new HashSet<JobApplication>();
            this.Jobs = new HashSet<Job>();
        }
    
        public int Id { get; set; }
        public int LookupTypeId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual ICollection<Graduate> Graduates { get; set; }
        public virtual ICollection<Graduate> Graduates1 { get; set; }
        public virtual ICollection<GraduateLanguage> GraduateLanguages { get; set; }
        public virtual ICollection<JobApplication> JobApplications { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
