CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Username] VARCHAR(50) NOT NULL, 
    [Salt] VARBINARY(8) NOT NULL, 
    [Hash] VARBINARY(64) NOT NULL, 
	[UserType] SMALLINT NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1
)
